
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores.graficoslexcup.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 2;
  public static final int IDD = 32;
  public static final int CORCHETEC = 11;
  public static final int CORCHETEA = 10;
  public static final int DECIMAL = 16;
  public static final int DIVISION = 5;
  public static final int DOPUNTO = 14;
  public static final int ETIQUETAS = 23;
  public static final int EJECUTAR = 31;
  public static final int LLAVEC = 9;
  public static final int LLAVEA = 8;
  public static final int POR = 4;
  public static final int TIPO = 28;
  public static final int PORCENTAJE = 26;
  public static final int VALORES = 24;
  public static final int BARRAS = 18;
  public static final int COMA = 12;
  public static final int TOTAL = 29;
  public static final int EOF = 0;
  public static final int DEF = 17;
  public static final int PIE = 19;
  public static final int EXTRA = 30;
  public static final int CANTIDAD = 25;
  public static final int error = 1;
  public static final int NUMERO = 15;
  public static final int EJEY = 22;
  public static final int PUNTOCOMA = 13;
  public static final int EJEX = 21;
  public static final int UNIR = 27;
  public static final int PARENTESISC = 7;
  public static final int TITULO = 20;
  public static final int MAS = 3;
  public static final int PARENTESISA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOS",
  "MAS",
  "POR",
  "DIVISION",
  "PARENTESISA",
  "PARENTESISC",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "COMA",
  "PUNTOCOMA",
  "DOPUNTO",
  "NUMERO",
  "DECIMAL",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "CANTIDAD",
  "PORCENTAJE",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "IDD"
  };
}

