
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores.graficoslexcup.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SIGNO_MAS = 3;
  public static final int SIGNO_CORCHETEC = 11;
  public static final int SIGNO_CORCHETEA = 10;
  public static final int SIGNO_COMA = 12;
  public static final int DECIMAL = 16;
  public static final int ETIQUETAS = 23;
  public static final int EJECUTAR = 31;
  public static final int TIPO = 28;
  public static final int PORCENTAJE = 26;
  public static final int VALORES = 24;
  public static final int BARRAS = 18;
  public static final int SIGNO_DIVISION = 5;
  public static final int SIGNO_DOPUNTO = 14;
  public static final int SIGNO_POR = 4;
  public static final int IDD_COMILLAS = 32;
  public static final int TOTAL = 29;
  public static final int EOF = 0;
  public static final int DEF = 17;
  public static final int PIE = 19;
  public static final int EXTRA = 30;
  public static final int CANTIDAD = 25;
  public static final int SIGNO_MENOS = 2;
  public static final int error = 1;
  public static final int NUMERO = 15;
  public static final int SIGNO_PARENTESISC = 7;
  public static final int SIGNO_PUNTOCOMA = 13;
  public static final int SIGNO_PARENTESISA = 6;
  public static final int EJEY = 22;
  public static final int EJEX = 21;
  public static final int UNIR = 27;
  public static final int TITULO = 20;
  public static final int SIGNO_LLAVEC = 9;
  public static final int SIGNO_LLAVEA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SIGNO_MENOS",
  "SIGNO_MAS",
  "SIGNO_POR",
  "SIGNO_DIVISION",
  "SIGNO_PARENTESISA",
  "SIGNO_PARENTESISC",
  "SIGNO_LLAVEA",
  "SIGNO_LLAVEC",
  "SIGNO_CORCHETEA",
  "SIGNO_CORCHETEC",
  "SIGNO_COMA",
  "SIGNO_PUNTOCOMA",
  "SIGNO_DOPUNTO",
  "NUMERO",
  "DECIMAL",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "CANTIDAD",
  "PORCENTAJE",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "IDD_COMILLAS"
  };
}

